(function(){
  'use strict';
  window.translations = {
  "en": {
    "chatbot-1": "OPS AI Chatbot",
    "chatbot-ph-2": "Type your message...",
    "chatbot-3": "I am human",
    "contact-1": "Contact Us - OPS • Chattia",
    "contact-2": "Contact Us",
    "contact-3": "Home",
    "contact-4": "Business Operations",
    "contact-5": "Contact Center",
    "contact-6": "IT Support",
    "contact-7": "Professionals",
    "contact-8": "Name",
    "contact-9": "Enter your name",
    "contact-10": "Email",
    "contact-11": "Enter your email",
    "contact-12": "Contact Number",
    "contact-13": "Enter your contact number",
    "contact-14": "Preferred Date",
    "contact-15": "Preferred Time",
    "contact-16": "What are you interested about?",
    "contact-17": "Business Operations",
    "contact-18": "Contact Center",
    "contact-19": "IT Support",
    "contact-20": "Professionals",
    "contact-21": "Comments",
    "contact-22": "What service are you interested in?",
    "contact-23": "Send",
    "join-1": "Join Us - OPS • Chattia",
    "join-2": "Join Us",
    "join-3": "Home",
    "join-4": "Business Operations",
    "join-5": "Contact Center",
    "join-6": "IT Support",
    "join-7": "Professionals",
    "join-8": "Name",
    "join-9": "Enter your name",
    "join-10": "Email",
    "join-11": "Enter your email",
    "join-12": "Phone",
    "join-13": "Enter your phone number",
    "join-14": "Skills",
    "join-15": "Accept",
    "join-16": "Edit",
    "join-17": "Education",
    "join-18": "Accept",
    "join-19": "Edit",
    "join-20": "Certification",
    "join-21": "Accept",
    "join-22": "Edit",
    "join-23": "Hobbies",
    "join-24": "Accept",
    "join-25": "Edit",
    "join-26": "What are you interested about?",
    "join-27": "Business Operations",
    "join-28": "Contact Center",
    "join-29": "IT Support",
    "join-30": "Professionals",
    "join-31": "Tell us about yourself",
    "join-32": "Tell us about yourself...",
    "join-33": "Submit",
    "join-34": "Home",
    "join-35": "Business Operations",
    "join-36": "Contact Center",
    "join-37": "IT Support",
    "join-38": "Professionals",
    "business-1": "Business Operations Optimization | [Your Company]",
    "business-2": "Business Operations",
    "business-3": "Optimize your processes for maximum efficiency.",
    "business-4": "Streamline Your Business Operations",
    "business-5": "Boost productivity and reduce inefficiencies with custom-tailored operational strategies.",
    "business-6": "Get a Free Efficiency Audit",
    "business-7": "Why Operational Optimization Matters",
    "business-8": "Busy teams waste up to 20% of time due to process friction. Our experts help identify and remove these barriers through strategic analysis, automation, and streamlined workflows.",
    "business-9": "What You’ll Gain",
    "business-10": "20–40% time savings with automation",
    "business-11": "Real-time reporting dashboards",
    "business-12": "Cross-department collaboration alignment",
    "business-13": "Proven Results",
    "business-14": "“Within 60 days, we slashed internal admin time by 30%. Their team made our systems smarter, not just faster.”",
    "business-15": "– COO, TechCo",
    "business-16": "Trusted by Siemens, Deloitte, HubSpot",
    "business-17": "Book Your Free Audit",
    "business-18": "Your Name",
    "business-19": "Your Email",
    "business-20": "Schedule Now",
    "contactcenter-1": "Contact Center Solutions | [Your Company]",
    "contactcenter-2": "Contact Center",
    "contactcenter-3": "Improve customer satisfaction with our expert support.",
    "contactcenter-4": "Reliable, Empathetic Contact Center Services",
    "contactcenter-5": "Deliver support that feels human — with efficiency and care, 24/7.",
    "contactcenter-6": "Request a Custom Quote",
    "contactcenter-7": "Why Clients Choose Us",
    "contactcenter-8": "Round-the-clock global coverage",
    "contactcenter-9": "Multilingual, empathetic agents",
    "contactcenter-10": "Custom escalation workflows",
    "contactcenter-11": "Built for Trust and Speed",
    "contactcenter-12": "We address 85% of inquiries in under 2 minutes and offer customizable SLAs. Clients trust us because we show up on time, every time — with clarity and care.",
    "contactcenter-13": "What Customers Say",
    "contactcenter-14": "“Our churn dropped by 18% in 90 days. The emotional intelligence of their reps is unmatched.”",
    "contactcenter-15": "– VP CX, HealthTech Firm",
    "contactcenter-16": "Client logos",
    "contactcenter-17": "See What We Can Do for You",
    "contactcenter-18": "Full Name",
    "contactcenter-19": "Business Email",
    "contactcenter-20": "Company",
    "contactcenter-21": "Request Quote",
    "itsupport-1": "IT Support Services | [Your Company]",
    "itsupport-2": "IT Support",
    "itsupport-3": "Reliable technical assistance to keep your systems running.",
    "itsupport-4": "Secure, Scalable IT Support for Growing Teams",
    "itsupport-5": "Minimize downtime and maximize performance — without hiring a full IT department.",
    "itsupport-6": "Get Free Assessment",
    "itsupport-7": "Our IT Support Tiers",
    "itsupport-8": "Basic: Ticket-based support (5‑hour response)",
    "itsupport-9": "Pro: Live chat + remote desktop (2‑hour response)",
    "itsupport-10": "Enterprise: Dedicated engineers + on‑call 24/7",
    "itsupport-11": "Client Story",
    "itsupport-12": "“We went from 6 support tickets per day to 1 — and our team morale shot up. Best decision this year.”",
    "itsupport-13": "– CTO, FinTech Startup",
    "itsupport-14": "Certifications & Compliance",
    "itsupport-15": "ISO, SOC2, HIPAA",
    "itsupport-16": "Our team is certified in ISO 27001, SOC2, and HIPAA — ensuring secure, enterprise‑grade support.",
    "itsupport-17": "Request Your Free IT Readiness Check",
    "itsupport-18": "Your Name",
    "itsupport-19": "Work Email",
    "itsupport-20": "Company Size",
    "itsupport-21": "Request Now",
    "professionals-1": "Professional Services | [Your Company]",
    "professionals-2": "Professionals",
    "professionals-3": "Connect with our team of certified professionals.",
    "professionals-4": "Unlock Expertise. Deliver Results.",
    "professionals-5": "Our consultants bring decades of experience to your biggest business challenges.",
    "professionals-6": "Book Free Strategy Call",
    "professionals-7": "We Specialize In:",
    "professionals-8": "Digital transformation & change management",
    "professionals-9": "Business continuity & risk planning",
    "professionals-10": "Revenue operations & analytics",
    "professionals-11": "Real Impact",
    "professionals-12": "“Their team didn’t just advise — they executed. We hit 120% of our revenue goal within two quarters.”",
    "professionals-13": "– CEO, B2B SaaS",
    "professionals-14": "Client logos",
    "professionals-15": "Limited-Time Offer",
    "professionals-16": "Book by July 31 and get a free 90-minute ops strategy session (normally $650).",
    "professionals-17": "Only 6 sessions left this month.",
    "professionals-18": "Get Started Now",
    "professionals-19": "Full Name",
    "professionals-20": "Business Email",
    "professionals-21": "Book Session"
  },
  "es": {
    "chatbot-1": "Chatbot OPS AI",
    "chatbot-ph-2": "Escriba su mensaje...",
    "chatbot-3": "Soy humano",
    "contact-1": "Contáctanos - OPS • Chattia",
    "contact-2": "Contáctanos",
    "contact-3": "Inicio",
    "contact-4": "Operaciones Empresariales",
    "contact-5": "Centro de Contacto",
    "contact-6": "Soporte Técnico",
    "contact-7": "Profesionales",
    "contact-8": "Nombre",
    "contact-9": "Ingresa tu nombre",
    "contact-10": "Correo",
    "contact-11": "Ingresa tu correo",
    "contact-12": "Teléfono",
    "contact-13": "Ingresa tu teléfono",
    "contact-14": "Fecha Preferida",
    "contact-15": "Hora Preferida",
    "contact-16": "¿Qué te interesa?",
    "contact-17": "Operaciones Empresariales",
    "contact-18": "Centro de Contacto",
    "contact-19": "Soporte Técnico",
    "contact-20": "Profesionales",
    "contact-21": "Comentarios",
    "contact-22": "¿Qué servicio te interesa?",
    "contact-23": "Enviar",
    "join-1": "Únete - OPS • Chattia",
    "join-2": "Únete a Nosotros",
    "join-3": "Inicio",
    "join-4": "Operaciones Empresariales",
    "join-5": "Centro de Contacto",
    "join-6": "Soporte Técnico",
    "join-7": "Profesionales",
    "join-8": "Nombre",
    "join-9": "Ingresa tu nombre",
    "join-10": "Correo",
    "join-11": "Ingresa tu correo",
    "join-12": "Teléfono",
    "join-13": "Ingresa tu teléfono",
    "join-14": "Habilidades",
    "join-15": "Aceptar",
    "join-16": "Editar",
    "join-17": "Educación",
    "join-18": "Aceptar",
    "join-19": "Editar",
    "join-20": "Certificaciones",
    "join-21": "Aceptar",
    "join-22": "Editar",
    "join-23": "Pasatiempos",
    "join-24": "Aceptar",
    "join-25": "Editar",
    "join-26": "¿Qué te interesa?",
    "join-27": "Operaciones Empresariales",
    "join-28": "Centro de Contacto",
    "join-29": "Soporte Técnico",
    "join-30": "Profesionales",
    "join-31": "Cuéntanos sobre ti",
    "join-32": "Cuéntanos sobre ti...",
    "join-33": "Enviar",
    "join-34": "Inicio",
    "join-35": "Operaciones Empresariales",
    "join-36": "Centro de Contacto",
    "join-37": "Soporte Técnico",
    "join-38": "Profesionales",
    "business-1": "Optimización de Operaciones Empresariales | [Su Empresa]",
    "business-2": "Operaciones Empresariales",
    "business-3": "Optimice sus procesos para obtener la máxima eficiencia.",
    "business-4": "Optimice Sus Operaciones Empresariales",
    "business-5": "Aumente la productividad y reduzca las ineficiencias con estrategias operativas a medida.",
    "business-6": "Obtenga una Auditoría de Eficiencia Gratis",
    "business-7": "Por Qué Importa la Optimización Operativa",
    "business-8": "Los equipos ocupados pierden hasta el 20% del tiempo debido a fricciones en los procesos. Nuestros expertos identifican y eliminan esas barreras mediante análisis estratégico, automatización y flujos de trabajo optimizados.",
    "business-9": "Lo Que Obtendrá",
    "business-10": "Ahorro de tiempo del 20–40% con automatización",
    "business-11": "Tableros de informes en tiempo real",
    "business-12": "Alineación de colaboración entre departamentos",
    "business-13": "Resultados Comprobados",
    "business-14": "“En 60 días, redujimos el tiempo administrativo interno en un 30%. Su equipo hizo nuestros sistemas más inteligentes, no solo más rápidos.”",
    "business-15": "– Director de Operaciones, TechCo",
    "business-16": "Con la confianza de Siemens, Deloitte, HubSpot",
    "business-17": "Reserve Su Auditoría Gratis",
    "business-18": "Su Nombre",
    "business-19": "Su Correo Electrónico",
    "business-20": "Programar Ahora",
    "contactcenter-1": "Soluciones de Centro de Contacto | [Su Empresa]",
    "contactcenter-2": "Centro de Contacto",
    "contactcenter-3": "Mejore la satisfacción del cliente con nuestro soporte experto.",
    "contactcenter-4": "Servicios de Centro de Contacto Confiables y Empáticos",
    "contactcenter-5": "Brinde soporte que se sienta humano — con eficiencia y atención, 24/7.",
    "contactcenter-6": "Solicite una Cotización Personalizada",
    "contactcenter-7": "Por Qué los Clientes Nos Eligen",
    "contactcenter-8": "Cobertura global las 24 horas",
    "contactcenter-9": "Agentes multilingües y empáticos",
    "contactcenter-10": "Flujos de trabajo de escalamiento personalizados",
    "contactcenter-11": "Diseñado para la Confianza y la Velocidad",
    "contactcenter-12": "Atendemos el 85% de las consultas en menos de 2 minutos y ofrecemos SLA personalizables. Los clientes confían en nosotros porque cumplimos a tiempo, cada vez — con claridad y atención.",
    "contactcenter-13": "Lo Que Dicen los Clientes",
    "contactcenter-14": "“Nuestra tasa de abandono cayó un 18% en 90 días. La inteligencia emocional de sus representantes no tiene igual.”",
    "contactcenter-15": "– VP de Experiencia del Cliente, Empresa HealthTech",
    "contactcenter-16": "Logotipos de clientes",
    "contactcenter-17": "Vea Lo Que Podemos Hacer por Usted",
    "contactcenter-18": "Nombre Completo",
    "contactcenter-19": "Correo Electrónico Empresarial",
    "contactcenter-20": "Empresa",
    "contactcenter-21": "Solicitar Cotización",
    "itsupport-1": "Servicios de Soporte TI | [Su Empresa]",
    "itsupport-2": "Soporte TI",
    "itsupport-3": "Asistencia técnica confiable para mantener sus sistemas en funcionamiento.",
    "itsupport-4": "Soporte TI Seguro y Escalable para Equipos en Crecimiento",
    "itsupport-5": "Minimice el tiempo de inactividad y maximice el rendimiento — sin contratar un departamento de TI completo.",
    "itsupport-6": "Obtenga Evaluación Gratuita",
    "itsupport-7": "Nuestros Niveles de Soporte TI",
    "itsupport-8": "Básico: Soporte por tickets (respuesta en 5 horas)",
    "itsupport-9": "Pro: Chat en vivo + escritorio remoto (respuesta en 2 horas)",
    "itsupport-10": "Enterprise: Ingenieros dedicados + disponibilidad 24/7",
    "itsupport-11": "Historia del Cliente",
    "itsupport-12": "“Pasamos de 6 tickets de soporte por día a 1 — y la moral de nuestro equipo se disparó. La mejor decisión de este año.”",
    "itsupport-13": "– CTO de Startup FinTech",
    "itsupport-14": "Certificaciones y Cumplimiento",
    "itsupport-15": "ISO, SOC2, HIPAA",
    "itsupport-16": "Nuestro equipo está certificado en ISO 27001, SOC2 y HIPAA — garantizando soporte seguro de calidad empresarial.",
    "itsupport-17": "Solicite Su Revisión Gratuita de Preparación TI",
    "itsupport-18": "Su Nombre",
    "itsupport-19": "Correo Electrónico Laboral",
    "itsupport-20": "Tamaño de la Empresa",
    "itsupport-21": "Solicitar Ahora",
    "professionals-1": "Servicios Profesionales | [Su Empresa]",
    "professionals-2": "Profesionales",
    "professionals-3": "Conéctese con nuestro equipo de profesionales certificados.",
    "professionals-4": "Desbloquee Conocimientos. Obtenga Resultados.",
    "professionals-5": "Nuestros consultores aportan décadas de experiencia a sus mayores desafíos empresariales.",
    "professionals-6": "Reserve Llamada de Estrategia Gratis",
    "professionals-7": "Nos Especializamos En:",
    "professionals-8": "Transformación digital y gestión del cambio",
    "professionals-9": "Continuidad del negocio y planificación de riesgos",
    "professionals-10": "Operaciones de ingresos y analítica",
    "professionals-11": "Impacto Real",
    "professionals-12": "“Su equipo no solo aconsejó, sino que ejecutó. Alcanzamos el 120% de nuestra meta de ingresos en dos trimestres.”",
    "professionals-13": "– CEO, SaaS B2B",
    "professionals-14": "Logotipos de clientes",
    "professionals-15": "Oferta por Tiempo Limitado",
    "professionals-16": "Reserve antes del 31 de julio y obtenga una sesión de estrategia de operaciones gratuita de 90 minutos (normalmente $650).",
    "professionals-17": "Solo quedan 6 sesiones este mes.",
    "professionals-18": "Comience Ahora",
    "professionals-19": "Nombre Completo",
    "professionals-20": "Correo Electrónico Empresarial",
    "professionals-21": "Reservar Sesión"
  }
};

  window.updateLanguage = function(lang){
    document.documentElement.lang = lang;
    const langMap = window.translations[lang] || {};
    document.querySelectorAll('[data-i18n]').forEach(el=>{
      const key = el.getAttribute('data-i18n');
      const val = langMap[key];
      if(!val) return;
      const tag = el.tagName.toLowerCase();
      if(tag==='input' || tag==='textarea') {
        el.placeholder = val;
      } else if(tag==='img') {
        el.alt = val;
      } else {
        el.textContent = val;
      }
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(el=>{
      const key = el.getAttribute('data-i18n-ph');
      const val = langMap[key];
      if(val) el.placeholder = val;
    });
  };

  // theme toggling handled in theme.js
})();
